import { useEffect, useRef, useState } from 'react'

// Maps viseme codes -> sprite paths, loaded from the manifest generated by
// scripts/generate_sprites.py. Falls back to the base character image if a
// sprite is missing so the UI degrades gracefully before sprites are generated.
type SpriteManifest = Record<string, string>

// How long to crossfade between two sprites (ms)
const FADE_MS = 60

// Between-paragraph idle cycle: alternate idle_1 and idle_2 every N ms
const IDLE_CYCLE_MS = 3200

interface Props {
  imageSrc: string
  viseme: string
  talking: boolean
}

export function CharacterCanvas({ imageSrc, viseme, talking }: Props) {
  const [manifest, setManifest] = useState<SpriteManifest | null>(null)
  const [manifestError, setManifestError] = useState(false)

  // Active sprite: what is currently displayed
  const [activeSprite, setActiveSprite] = useState(imageSrc)
  // Previous sprite: fades out while active fades in
  const [prevSprite, setPrevSprite] = useState<string | null>(null)
  const [fading, setFading] = useState(false)

  const idleTimerRef = useRef<number | null>(null)
  const idleIndexRef = useRef(0)
  const fadingRef = useRef(false)

  // Load sprite manifest once
  useEffect(() => {
    fetch('/sprites/manifest.json')
      .then((r) => {
        if (!r.ok) throw new Error('manifest missing')
        return r.json()
      })
      .then((data: SpriteManifest) => setManifest(data))
      .catch(() => setManifestError(true))
  }, [])

  function spriteFor(v: string): string {
    if (!manifest) return imageSrc
    return manifest[v] ?? imageSrc
  }

  function crossfadeTo(next: string) {
    if (fadingRef.current) return
    fadingRef.current = true
    setFading(true)
    setPrevSprite((cur) => cur ?? imageSrc)
    setActiveSprite(next)
    setTimeout(() => {
      setPrevSprite(null)
      setFading(false)
      fadingRef.current = false
    }, FADE_MS)
  }

  // React to viseme changes while talking
  useEffect(() => {
    if (manifest == null && !manifestError) return
    if (talking) {
      crossfadeTo(spriteFor(viseme))
    }
  }, [viseme, talking, manifest])

  // When talking stops, return to sil (or base image)
  useEffect(() => {
    if (!talking) {
      crossfadeTo(spriteFor('sil'))
    }
  }, [talking, manifest])

  // Idle shift loop — only runs if idle sprites exist in the manifest
  useEffect(() => {
    if (talking || manifest == null || !manifest['idle_1']) {
      if (idleTimerRef.current !== null) {
        clearInterval(idleTimerRef.current)
        idleTimerRef.current = null
      }
      return
    }

    idleTimerRef.current = window.setInterval(() => {
      idleIndexRef.current = (idleIndexRef.current + 1) % 2
      const key = `idle_${idleIndexRef.current + 1}`
      const sprite = manifest[key]
      if (sprite) crossfadeTo(sprite)
    }, IDLE_CYCLE_MS)

    return () => {
      if (idleTimerRef.current !== null) clearInterval(idleTimerRef.current)
    }
  }, [talking, manifest])

  // Before sprites are ready, render the base image directly
  if (manifest == null) {
    return (
      <img
        src={imageSrc}
        alt="study buddy"
        className="max-h-full max-w-full object-contain"
      />
    )
  }

  return (
    <div className="relative max-h-full max-w-full flex items-center justify-center">
      {/* Previous frame fades out */}
      {prevSprite && fading && (
        <img
          key={prevSprite + '-prev'}
          src={prevSprite}
          alt=""
          aria-hidden
          className="absolute inset-0 max-h-full max-w-full object-contain transition-opacity"
          style={{ opacity: 0, transitionDuration: `${FADE_MS}ms` }}
        />
      )}
      {/* Active frame fades in */}
      <img
        key={activeSprite}
        src={activeSprite}
        alt="study buddy"
        className="max-h-full max-w-full object-contain transition-opacity"
        style={{
          opacity: 1,
          transitionDuration: `${FADE_MS}ms`,
        }}
      />
    </div>
  )
}
